### PR TITLE
Added Goatcounter events for About page and FAQ page

### PR DESCRIPTION
**Pull request by NeedADispenserHere**

### CODE REVIEW

**Comment by lil5** [comment]
Maybe prepend it with "accessed page <name>"

**Comment by NeedADispenserHere** [comment]
I changed the counter titles to "Accessed Page:About" and "Accessed Page:FAQ"

**Review by lil5 — APPROVED** [review]
Looks great 👍

**Comment by lil5** [comment]
@NeedADispenserHere I needed to wrap the code in a useEffect otherwise the code would run for each re-render of the page, even those running inside /about/ or /faq/ routes

Heres some documentation about useEffect and why I needed to use it https://react.dev/learn/lifecycle-of-reactive-effects#what-an-effect-with-empty-dependencies-means

**Pull request merged**
